name: Flutter Debug Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'Test'
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter app (debug)
        run: flutter build apk --debug --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apks
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
